// Generated mapping with updated eBird nomenclature
const Map<String, String> scientificToCommon = {
  "Haemorhous cassinii": "Cassin's Finch",
  "Aramus guarauna": "Limpkin",
  "Rupornis magnirostris": "Roadside Hawk",
  "Cyanocitta cristata": "Blue Jay",
  "Cyanocitta stelleri": "Steller's Jay",
  "Balearica regulorum": "Gray Crowned-Crane",
  "Pyrocephalus rubinus": "Vermilion Flycatcher",
  "Recurvirostra americana": "American Avocet",
  "Ardeotis kori": "Kori Bustard",
  "Pica nuttalli": "Yellow-billed Magpie",
  "Perisoreus canadensis": "Canada Jay",
  "Antigone canadensis": "Sandhill Crane",
  "Parkesia noveboracensis": "Northern Waterthrush",
  "Ardea herodias occidentalis": "Great Blue Heron (Great White)",
  "Porzana carolina": "Sora",
  "Anas platyrhynchos diazi": "Mallard",
  "Motacilla cinerea": "Gray Wagtail",
  "Empidonax difficilis": "Western Flycatcher",
  "Empidonax minimus": "Least Flycatcher",
  "Empidonax fulvifrons": "Buff-breasted Flycatcher",
  "Empidonax traillii": "Willow Flycatcher",
  "Empidonax hammondii": "Hammond's Flycatcher",
  "Empidonax occidentalis": "Empidonax occidentalis",
  "Rallus limicola": "Virginia Rail",
  "Grus grus": "Common Crane",
  "Quiscalus major": "Boat-tailed Grackle",
  "Branta leucopsis": "Barnacle Goose",
  "Cyanocorax yucatanicus": "Yucatan Jay",
  "Cyanocorax yncas": "Green Jay",
  "Oceanites oceanicus": "Wilson's Storm-Petrel",
  "Quiscalus niger": "Greater Antillean Grackle",
  "Psilorhinus morio": "Brown Jay",
  "Megarynchus pitangua": "Boat-billed Flycatcher",
  "Gallinula tenebrosa": "Dusky Moorhen",
  "Gallus gallus domesticus": "Red Junglefowl",
  "Numida meleagris": "Helmeted Guineafowl",
  "Junco hyemalis caniceps": "Dark-eyed Junco (Gray-headed)",
  "Tyrannus vociferans": "Cassin's Kingbird",
  "Tyrannus tyrannus": "Eastern Kingbird",
  "Tyrannus forficatus": "Scissor-tailed Flycatcher",
  "Tyrannus crassirostris": "Thick-billed Kingbird",
  "Tyrannus verticalis": "Western Kingbird",
  "Tyrannus savana": "Fork-tailed Flycatcher",
  "Gallirallus australis": "Weka",
  "Calocitta formosa": "White-throated Magpie-Jay",
  "Calocitta colliei": "Black-throated Magpie-Jay",
  "Fulica americana": "American Coot",
  "Pachyramphus aglaiae": "Rose-throated Becard",
  "Buteo lagopus": "Rough-legged Hawk",
  "Cygnus atratus": "Black Swan",
  "Philesturnus rufusater": "North Island Saddleback",
  "Larus marinus": "Great Black-backed Gull",
  "Pitangus sulphuratus": "Great Kiskadee",
  "Anas rubripes": "American Black Duck",
  "Anthus novaeseelandiae novaeseelandiae": "",
  "Sayornis phoebe": "Eastern Phoebe",
  "Sayornis nigricans": "Black Phoebe",
  "Tityra semifasciata": "Masked Tityra",
  "Dryocopus lineatus": "Lineated Woodpecker",
  "Porphyrio melanotus": "Australasian Swamphen",
  "Anas bahamensis": "White-cheeked Pintail",
  "Egretta novaehollandiae": "White-faced Heron",
  "Anas crecca carolinensis": "Green-winged Teal (American)",
  "Alectoris chukar": "Chukar",
  "Tachybaptus dominicus": "Least Grebe",
  "Artemisiospiza belli": "Bell's Sparrow",
  "Gallus gallus": "Red Junglefowl",
  "Cardinalis sinuatus": "Pyrrhuloxia",
  "Cardinalis cardinalis": "Northern Cardinal",
  "Melospiza lincolnii": "Lincoln's Sparrow",
  "Podilymbus podiceps": "Pied-billed Grebe",
  "Melospiza georgiana": "Swamp Sparrow",
  "Meleagris gallopavo": "Wild Turkey",
  "Meleagris ocellata": "Ocellated Turkey",
  "Lagopus lagopus": "Willow Ptarmigan",
  "Spizella atrogularis": "Black-chinned Sparrow",
  "Pyrrhocorax graculus": "Yellow-billed Chough",
  "Spizella breweri": "Brewer's Sparrow",
  "Sialia currucoides": "Mountain Bluebird",
  "Spizella pusilla": "Field Sparrow",
  "Anas superciliosa": "Pacific Black Duck",
  "Passerella iliaca": "Fox Sparrow",
  "Phoenicopterus ruber": "American Flamingo",
  "Sylvia atricapilla": "Eurasian Blackcap",
  "Vireo bellii": "Bell's Vireo",
  "Vireo plumbeus": "Plumbeous Vireo",
  "Vireo philadelphicus": "Philadelphia Vireo",
  "Vireo flavifrons": "Yellow-throated Vireo",
  "Vireo olivaceus": "Red-eyed Vireo",
  "Zonotrichia querula": "Harris's Sparrow",
  "Vireo huttoni": "Hutton's Vireo",
  "Zonotrichia albicollis": "White-throated Sparrow",
  "Zonotrichia atricapilla": "Golden-crowned Sparrow",
  "Emberiza citrinella": "Yellowhammer",
  "Bucephala islandica": "Barrow's Goldeneye",
  "Emberiza schoeniclus": "Reed Bunting",
  "Vireo gilvus": "Warbling Vireo",
  "Serinus serinus": "European Serin",
  "Serinus mozambicus": "Serinus mozambicus",
  "Lophura leucomelanos": "Kalij Pheasant",
  "Euphonia elegantissima": "Euphonia elegantissima",
  "Euphonia hirundinacea": "Yellow-throated Euphonia",
  "Euphonia affinis": "Scrub Euphonia",
  "Agelaius tricolor": "Tricolored Blackbird",
  "Momotus lessonii": "Lesson's Motmot",
  "Zosterops japonicus": "Warbling White-eye",
  "Phalacrocorax pelagicus": "Phalacrocorax pelagicus",
  "Icterus cucullatus": "Hooded Oriole",
  "Icterus graduacauda": "Audubon's Oriole",
  "Motacilla aguimp": "African Pied Wagtail",
  "Anas superciliosa × platyrhynchos": "Pacific Black Duck",
  "Icterus pustulatus": "Streak-backed Oriole",
  "Icterus gularis": "Altamira Oriole",
  "Carduelis cannabina": "Carduelis cannabina",
  "Catharus minimus": "Gray-cheeked Thrush",
  "Amaurornis phoenicurus": "White-breasted Waterhen",
  "Pavo cristatus": "Indian Peafowl",
  "Rallus crepitans": "Clapper Rail",
  "Nestor meridionalis septentrionalis": "",
  "Pipilo chlorurus": "Green-tailed Towhee",
  "Pipilo maculatus": "Spotted Towhee",
  "Pipilo erythrophthalmus": "Eastern Towhee",
  "Cairina moschata domestica": "Muscovy Duck",
  "Phalacrocorax varius": "Pied Cormorant",
  "Picoides dorsalis": "American Three-toed Woodpecker",
  "Picoides nuttallii": "Picoides nuttallii",
  "Picoides scalaris": "Picoides scalaris",
  "Callipepla gambelii": "Gambel's Quail",
  "Pyrrhula pyrrhula": "Eurasian Bullfinch",
  "Phalacrocorax brasilianus": "Phalacrocorax brasilianus",
  "Picoides pubescens": "Picoides pubescens",
  "Colinus virginianus": "Northern Bobwhite",
  "Sporophila torqueola": "Cinnamon-rumped Seedeater",
  "Picoides villosus": "Picoides villosus",
  "Calidris pusilla": "Semipalmated Sandpiper",
  "Picoides arcticus": "Black-backed Woodpecker",
  "Aythya marila": "Greater Scaup",
  "Phaethon aethereus": "Red-billed Tropicbird",
  "Sturnella magna": "Eastern Meadowlark",
  "Melopsittacus undulatus": "Budgerigar",
  "Aythya affinis": "Lesser Scaup",
  "Aythya novaeseelandiae": "New Zealand Scaup",
  "Cyrtonyx montezumae": "Montezuma Quail",
  "Pelecanus occidentalis": "Brown Pelican",
  "Cinclus cinclus": "White-throated Dipper",
  "Chen rossii": "Chen rossii",
  "Callipepla californica": "California Quail",
  "Quiscalus quiscula": "Common Grackle",
  "Quiscalus mexicanus": "Great-tailed Grackle",
  "Callipepla squamata": "Scaled Quail",
  "Dryocopus pileatus": "Pileated Woodpecker",
  "Passerina caerulea": "Blue Grosbeak",
  "Amazilia beryllina": "Amazilia beryllina",
  "Geothlypis trichas": "Common Yellowthroat",
  "Trogon melanocephalus": "Black-headed Trogon",
  "Sylvia communis": "Sylvia communis",
  "Pinicola enucleator": "Pine Grosbeak",
  "Coccothraustes vespertinus": "Evening Grosbeak",
  "Coccothraustes coccothraustes": "Hawfinch",
  "Vermivora chrysoptera": "Golden-winged Warbler",
  "Opisthocomus hoazin": "Hoatzin",
  "Setophaga coronata coronata": "Yellow-rumped Warbler (Myrtle)",
  "Diglossa baritula": "Cinnamon-bellied Flowerpiercer",
  "Saltator coerulescens": "Bluish-gray Saltator",
  "Saltator atriceps": "Black-headed Saltator",
  "Sicalis flaveola": "Saffron Finch",
  "Aix galericulata": "Mandarin Duck",
  "Junco hyemalis hyemalis": "",
  "Eupsittula canicularis": "Orange-fronted Parakeet",
  "Microcarbo melanoleucos": "Little Pied Cormorant",
  "Piranga rubra": "Summer Tanager",
  "Piranga olivacea": "Scarlet Tanager",
  "Piranga flava": "Hepatic Tanager",
  "Amphispiza bilineata": "Black-throated Sparrow",
  "Larus dominicanus": "Kelp Gull",
  "Piaya cayana": "Squirrel Cuckoo",
  "Aimophila ruficeps": "Rufous-crowned Sparrow",
  "Melanerpes lewis": "Lewis's Woodpecker",
  "Melanerpes uropygialis": "Gila Woodpecker",
  "Passerculus sandwichensis": "Savannah Sparrow",
  "Melanerpes pucherani": "Black-cheeked Woodpecker",
  "Salpinctes obsoletus": "Rock Wren",
  "Melanerpes carolinus": "Red-bellied Woodpecker",
  "Melanerpes chrysogenys": "Golden-cheeked Woodpecker",
  "Melanerpes formicivorus": "Acorn Woodpecker",
  "Colaptes auratus": "Northern Flicker",
  "Basileuterus rufifrons": "Rufous-capped Warbler",
  "Larus michahellis": "Yellow-legged Gull",
  "Ramphocelus passerinii": "Scarlet-rumped Tanager",
  "Athene cunicularia": "Burrowing Owl",
  "Branta hutchinsii": "Cackling Goose",
  "Fringilla montifringilla": "Brambling",
  "Fringilla coelebs": "Common Chaffinch",
  "Junco hyemalis": "Dark-eyed Junco",
  "Cuculus canorus": "Common Cuckoo",
  "Junco phaeonotus": "Yellow-eyed Junco",
  "Ammodramus nelsoni": "Ammodramus nelsoni",
  "Ammodramus savannarum": "Grasshopper Sparrow",
  "Ammodramus maritimus": "Ammodramus maritimus",
  "Coccyzus erythropthalmus": "Black-billed Cuckoo",
  "Coccyzus minor": "Mangrove Cuckoo",
  "Coccyzus americanus": "Yellow-billed Cuckoo",
  "Nucifraga columbiana": "Clark's Nutcracker",
  "Crotophaga sulcirostris": "Groove-billed Ani",
  "Pooecetes gramineus": "Vesper Sparrow",
  "Arremonops rufivirgatus": "Olive Sparrow",
  "Geococcyx californianus": "Greater Roadrunner",
  "Geococcyx velox": "Lesser Roadrunner",
  "Coereba flaveola": "Bananaquit",
  "Passerina ciris": "Painted Bunting",
  "Alectura lathami": "Australian Brushturkey",
  "Passerina leclancherii": "Orange-breasted Bunting",
  "Passerina amoena": "Lazuli Bunting",
  "Icteria virens": "Yellow-breasted Chat",
  "Crax rubra": "Great Curassow",
  "Penelope purpurascens": "Crested Guan",
  "Copsychus malabaricus": "White-rumped Shama",
  "Paroaria capitata": "Yellow-billed Cardinal",
  "Cyanerpes cyaneus": "Red-legged Honeycreeper",
  "Microcarbo melanoleucos brevirostris": "",
  "Sphyrapicus thyroideus": "Williamson's Sapsucker",
  "Pheucticus ludovicianus": "Rose-breasted Grosbeak",
  "Sphyrapicus ruber": "Red-breasted Sapsucker",
  "Pheucticus melanocephalus": "Black-headed Grosbeak",
  "Sphyrapicus nuchalis": "Red-naped Sapsucker",
  "Ortalis poliocephala": "West Mexican Chachalaca",
  "Ortalis vetula": "Plain Chachalaca",
  "Corvus albus": "Pied Crow",
  "Mniotilta varia": "Black-and-white Warbler",
  "Volatinia jacarina": "Blue-black Grassquit",
  "Thraupis palmarum": "Palm Tanager",
  "Momotus mexicanus": "Russet-crowned Motmot",
  "Euphagus cyanocephalus": "Brewer's Blackbird",
  "Cacatua galerita": "Sulphur-crested Cockatoo",
  "Junco hyemalis oreganus": "",
  "Pluvialis fulva": "Pacific Golden-Plover",
  "Molothrus aeneus": "Bronzed Cowbird",
  "Molothrus ater": "Brown-headed Cowbird",
  "Merops pusillus": "Little Bee-eater",
  "Merops apiaster": "European Bee-eater",
  "Pteroglossus torquatus": "Collared Aracari",
  "Loxia curvirostra": "Red Crossbill",
  "Merops orientalis": "Asian Green Bee-eater",
  "Loxia leucoptera": "White-winged Crossbill",
  "Coracias garrulus": "European Roller",
  "Coracias caudatus": "Lilac-breasted Roller",
  "Coracias benghalensis": "Indian Roller",
  "Xanthocephalus xanthocephalus": "Yellow-headed Blackbird",
  "Chondestes grammacus": "Lark Sparrow",
  "Dolichonyx oryzivorus": "Bobolink",
  "Pandion haliaetus": "Osprey",
  "Phainopepla nitens": "Phainopepla",
  "Tyrannus couchii": "Couch's Kingbird",
  "Phylloscopus collybita": "Common Chiffchaff",
  "Circus cyaneus hudsonius": "Hen Harrier",
  "Grallina cyanoleuca": "Magpie-lark",
  "Plectrophenax nivalis": "Snow Bunting",
  "Calamospiza melanocorys": "Lark Bunting",
  "Regulus calendula": "Regulus calendula",
  "Regulus ignicapilla": "Common Firecrest",
  "Regulus regulus": "Goldcrest",
  "Regulus satrapa": "Golden-crowned Kinglet",
  "Tyrannus melancholicus": "Tropical Kingbird",
  "Pelecanus conspicillatus": "Australian Pelican",
  "Aulacorhynchus prasinus": "Northern Emerald-Toucanet",
  "Todiramphus sanctus": "Sacred Kingfisher",
  "Icterus bullockii": "Bullock's Oriole",
  "Spiza americana": "Dickcissel",
  "Tyrannus dominicensis": "Gray Kingbird",
  "Chlidonias niger": "Black Tern",
  "Oriturus superciliosus": "Striped Sparrow",
  "Psarocolius montezuma": "Montezuma Oropendola",
  "Turdus pilaris": "Fieldfare",
  "Notiomystis cincta": "Stitchbird",
  "Sagittarius serpentarius": "Secretarybird",
  "Psittacula krameri": "Rose-ringed Parakeet",
  "Platycercus eximius": "Eastern Rosella",
  "Protonotaria citrea": "Prothonotary Warbler",
  "Megaceryle torquata": "Ringed Kingfisher",
  "Nestor meridionalis": "New Zealand Kaka",
  "Amazona viridigenalis": "Red-crowned Parrot",
  "Amazona albifrons": "White-fronted Parrot",
  "Amazona oratrix": "Yellow-headed Parrot",
  "Saxicola rubetra": "Whinchat",
  "Ara militaris": "Military Macaw",
  "Spizelloides arborea": "American Tree Sparrow",
  "Ceryle rudis": "Pied Kingfisher",
  "Chloroceryle aenea": "American Pygmy Kingfisher",
  "Chloroceryle amazona": "Amazon Kingfisher",
  "Myiozetetes similis": "Social Flycatcher",
  "Toxostoma curvirostre": "Curve-billed Thrasher",
  "Megaceryle alcyon": "Belted Kingfisher",
  "Eremophila alpestris": "Horned Lark",
  "Alisterus scapularis": "Australian King-Parrot",
  "Cinnyris jugularis": "Garden Sunbird",
  "Xiphorhynchus flavigaster": "Ivory-billed Woodcreeper",
  "Jacana jacana": "Wattled Jacana",
  "Phalaropus fulicarius": "Red Phalarope",
  "Streptopelia turtur": "European Turtle-Dove",
  "Pica hudsonia": "Black-billed Magpie",
  "Corvus cornix": "Hooded Crow",
  "Myiopsitta monachus": "Monk Parakeet",
  "Streptopelia decaocto": "Eurasian Collared-Dove",
  "Piranga ludoviciana": "Western Tanager",
  "Ixobrychus exilis": "Least Bittern",
  "Auriparus flaviceps": "Verdin",
  "Geothlypis tolmiei": "MacGillivray's Warbler",
  "Columba livia": "Rock Pigeon",
  "Setophaga citrina": "Hooded Warbler",
  "Setophaga cerulea": "Cerulean Warbler",
  "Columba palumbus": "Common Wood-Pigeon",
  "Piranga bidentata": "Flame-colored Tanager",
  "Patagioenas leucocephala": "White-crowned Pigeon",
  "Patagioenas fasciata": "Band-tailed Pigeon",
  "Patagioenas flavirostris": "Red-billed Pigeon",
  "Setophaga discolor": "Prairie Warbler",
  "Chordeiles minor": "Common Nighthawk",
  "Chordeiles acutipennis": "Lesser Nighthawk",
  "Platalea leucorodia": "Eurasian Spoonbill",
  "Phalaenoptilus nuttallii": "Common Poorwill",
  "Haemorhous mexicanus": "House Finch",
  "Haemorhous purpureus": "Purple Finch",
  "Nyctidromus albicollis": "Common Pauraque",
  "Campephilus guatemalensis": "Pale-billed Woodpecker",
  "Toxostoma rufum": "Brown Thrasher",
  "Leptotila verreauxi": "White-tipped Dove",
  "Nyctibius jamaicensis": "Northern Potoo",
  "Anas penelope": "Anas penelope",
  "Buteo plagiatus": "Gray Hawk",
  "Selasphorus calliope": "Calliope Hummingbird",
  "Megascops kennicottii": "Western Screech-Owl",
  "Porphyrio poliocephalus": "Gray-headed Swamphen",
  "Megascops asio": "Eastern Screech-Owl",
  "Zenaida auriculata": "Eared Dove",
  "Hymenolaimus malacorhynchos": "Blue Duck",
  "Setophaga caerulescens": "Black-throated Blue Warbler",
  "Camptostoma imberbe": "Northern Beardless-Tyrannulet",
  "Caracara plancus": "Crested Caracara",
  "Columbina passerina": "Common Ground Dove",
  "Eupsittula nana": "Olive-throated Parakeet",
  "Nestor notabilis": "Kea",
  "Columbina talpacoti": "Ruddy Ground Dove",
  "Geopelia striata": "Zebra Dove",
  "Athene noctua": "Little Owl",
  "Crotophaga ani": "Smooth-billed Ani",
  "Sialia sialis": "Eastern Bluebird",
  "Platalea alba": "African Spoonbill",
  "Bubo virginianus": "Great Horned Owl",
  "Petrochelidon fulva": "Cave Swallow",
  "Progne subis": "Purple Martin",
  "Setophaga coronata auduboni": "Yellow-rumped Warbler (Audubon's)",
  "Hirundo neoxena": "Welcome Swallow",
  "Hirundo rustica": "Barn Swallow",
  "Calidris virgata": "Surfbird",
  "Calidris pugnax": "Ruff",
  "Platalea regia": "Royal Spoonbill",
  "Tachycineta thalassina": "Violet-green Swallow",
  "Bostrychia hagedash": "Hadada Ibis",
  "Riparia riparia": "Bank Swallow",
  "Eudocimus albus": "White Ibis",
  "Plegadis falcinellus": "Glossy Ibis",
  "Plegadis chihi": "White-faced Ibis",
  "Corvus corax": "Common Raven",
  "Stelgidopteryx serripennis": "Northern Rough-winged Swallow",
  "Sula dactylatra": "Masked Booby",
  "Sula sula": "Red-footed Booby",
  "Sula leucogaster": "Brown Booby",
  "Morus serrator": "Australasian Gannet",
  "Eudyptula minor": "Little Penguin",
  "Megadyptes antipodes": "Yellow-eyed Penguin",
  "Scopus umbretta": "Hamerkop",
  "Troglodytes troglodytes": "Eurasian Wren",
  "Calidris canutus": "Red Knot",
  "Lanius collurio": "Red-backed Shrike",
  "Calidris bairdii": "Baird's Sandpiper",
  "Meleagris gallopavo intermedia": "",
  "Calidris mauri": "Western Sandpiper",
  "Calidris maritima": "Purple Sandpiper",
  "Calidris alpina": "Dunlin",
  "Calidris ferruginea": "Curlew Sandpiper",
  "Calidris melanotos": "Pectoral Sandpiper",
  "Limnodromus griseus": "Short-billed Dowitcher",
  "Malurus cyaneus": "Superb Fairywren",
  "Tringa nebularia": "Common Greenshank",
  "Todiramphus sanctus vagans": "Sacred Kingfisher (New Zealand)",
  "Tringa ochropus": "Green Sandpiper",
  "Tringa glareola": "Wood Sandpiper",
  "Tringa melanoleuca": "Greater Yellowlegs",
  "Tringa flavipes": "Lesser Yellowlegs",
  "Numenius arquata": "Eurasian Curlew",
  "Numenius phaeopus": "Whimbrel",
  "Phalacrocorax carbo novaehollandiae": "Great Cormorant (Australasian)",
  "Petroica macrocephala macrocephala": "",
  "Petroica australis longipes": "South Island Robin",
  "Prosthemadera novaeseelandiae novaeseelandiae": "",
  "Asio flammeus": "Short-eared Owl",
  "Rhipidura fuliginosa fuliginosa": "",
  "Scolopax minor": "American Woodcock",
  "Arenaria interpres": "Ruddy Turnstone",
  "Arenaria melanocephala": "Black Turnstone",
  "Rhipidura fuliginosa placabilis": "",
  "Limosa limosa": "Black-tailed Godwit",
  "Limosa haemastica": "Hudsonian Godwit",
  "Limosa fedoa": "Marbled Godwit",
  "Phalaropus lobatus": "Red-necked Phalarope",
  "Bartramia longicauda": "Upland Sandpiper",
  "Limosa lapponica": "Bar-tailed Godwit",
  "Aegolius acadicus": "Northern Saw-whet Owl",
  "Actitis hypoleucos": "Common Sandpiper",
  "Trichoglossus haematodus": "Coconut Lorikeet",
  "Surnia ulula": "Northern Hawk Owl",
  "Polioptila caerulea": "Blue-gray Gnatcatcher",
  "Spizella passerina": "Chipping Sparrow",
  "Pycnonotus jocosus": "Red-whiskered Bulbul",
  "Passerina cyanea": "Indigo Bunting",
  "Passerina versicolor": "Varied Bunting",
  "Manorina melanocephala": "Noisy Miner",
  "Ocyphaps lophotes": "Crested Pigeon",
  "Jabiru mycteria": "Jabiru",
  "Pycnonotus cafer": "Red-vented Bulbul",
  "Anser cygnoides domesticus": "Swan Goose",
  "Picus viridis": "Eurasian Green Woodpecker",
  "Phoebastria nigripes": "Black-footed Albatross",
  "Struthio camelus": "Common Ostrich",
  "Phoebastria immutabilis": "Laysan Albatross",
  "Fulmarus glacialis": "Northern Fulmar",
  "Francolinus pondicerianus": "Francolinus pondicerianus",
  "Cynanthus latirostris": "Broad-billed Hummingbird",
  "Podiceps nigricollis": "Eared Grebe",
  "Podiceps cristatus": "Great Crested Grebe",
  "Podiceps auritus": "Horned Grebe",
  "Dendrocopos major": "Great Spotted Woodpecker",
  "Podiceps grisegena": "Red-necked Grebe",
  "Tachybaptus ruficollis": "Little Grebe",
  "Charadrius montanus": "Charadrius montanus",
  "Phalacrocorax auritus": "Phalacrocorax auritus",
  "Phalacrocorax carbo": "Great Cormorant",
  "Phalacrocorax penicillatus": "Phalacrocorax penicillatus",
  "Aechmophorus clarkii": "Clark's Grebe",
  "Pelecanus onocrotalus": "Great White Pelican",
  "Pelecanus erythrorhynchos": "American White Pelican",
  "Zenaida macroura": "Mourning Dove",
  "Vanellus miles": "Masked Lapwing",
  "Larus occidentalis": "Western Gull",
  "Trogon massena": "Slaty-tailed Trogon",
  "Larus thayeri": "Larus thayeri",
  "Larus heermanni": "Heermann's Gull",
  "Larus livens": "Yellow-footed Gull",
  "Larus canus": "Common Gull",
  "Larus glaucoides": "Iceland Gull",
  "Larus delawarensis": "Ring-billed Gull",
  "Trogon collaris": "Collared Trogon",
  "Zenaida asiatica": "White-winged Dove",
  "Larus fuscus": "Lesser Black-backed Gull",
  "Larus californicus": "California Gull",
  "Prosthemadera novaeseelandiae": "Tui",
  "Trogon elegans": "Elegant Trogon",
  "Larus glaucescens": "Glaucous-winged Gull",
  "Trogon citreolus": "Citreoline Trogon",
  "Cepphus columba": "Pigeon Guillemot",
  "Himantopus leucocephalus": "Pied Stilt",
  "Cepphus grylle": "Black Guillemot",
  "Anthornis melanura": "New Zealand Bellbird",
  "Leptoptilos crumenifer": "Marabou Stork",
  "Threskiornis moluccus": "Threskiornis moluccus",
  "Thraupis episcopus": "Blue-gray Tanager",
  "Geranoaetus albicaudatus": "White-tailed Hawk",
  "Sterna paradisaea": "Arctic Tern",
  "Sterna hirundo": "Common Tern",
  "Sterna forsteri": "Forster's Tern",
  "Lanius excubitor": "Great Gray Shrike",
  "Pharomachrus mocinno": "Resplendent Quetzal",
  "Sterna striata": "White-fronted Tern",
  "Stercorarius parasiticus": "Parasitic Jaeger",
  "Stercorarius pomarinus": "Pomarine Jaeger",
  "Anas gracilis": "Gray Teal",
  "Rissa tridactyla": "Black-legged Kittiwake",
  "Rynchops niger": "Black Skimmer",
  "Alca torda": "Razorbill",
  "Fratercula arctica": "Atlantic Puffin",
  "Fratercula cirrhata": "Tufted Puffin",
  "Turdus merula": "Eurasian Blackbird",
  "Turdus plumbeus": "Red-legged Thrush",
  "Turdus grayi": "Clay-colored Thrush",
  "Turdus migratorius": "American Robin",
  "Turdus viscivorus": "Mistle Thrush",
  "Cerorhinca monocerata": "Rhinoceros Auklet",
  "Turdus philomelos": "Song Thrush",
  "Galbula ruficauda": "Rufous-tailed Jacamar",
  "Jacana spinosa": "Northern Jacana",
  "Saxicola rubicola": "European Stonechat",
  "Upupa epops": "Eurasian Hoopoe",
  "Euphagus carolinus": "Rusty Blackbird",
  "Gavia pacifica": "Pacific Loon",
  "Mimus gilvus": "Tropical Mockingbird",
  "Passer italiae": "Italian Sparrow",
  "Gavia immer": "Common Loon",
  "Gavia stellata": "Red-throated Loon",
  "Oenanthe oenanthe": "Northern Wheatear",
  "Fregata magnificens": "Magnificent Frigatebird",
  "Fregata minor": "Great Frigatebird",
  "Falco subbuteo": "Eurasian Hobby",
  "Falco mexicanus": "Prairie Falcon",
  "Falco femoralis": "Aplomado Falcon",
  "Falco peregrinus": "Peregrine Falcon",
  "Falco rufigularis": "Bat Falcon",
  "Falco sparverius": "American Kestrel",
  "Strix varia": "Barred Owl",
  "Falco columbarius": "Merlin",
  "Gallinula chloropus": "Eurasian Moorhen",
  "Cardellina pusilla": "Wilson's Warbler",
  "Catharus ustulatus": "Swainson's Thrush",
  "Falco novaeseelandiae": "New Zealand Falcon",
  "Catharus guttatus": "Hermit Thrush",
  "Catharus fuscescens": "Veery",
  "Caracara cheriway": "Caracara cheriway",
  "Herpetotheres cachinnans": "Laughing Falcon",
  "Calcarius lapponicus": "Lapland Longspur",
  "Milvago chimachima": "Milvago chimachima",
  "Ciconia ciconia": "White Stork",
  "Mycteria americana": "Wood Stork",
  "Mycteria ibis": "Yellow-billed Stork",
  "Sialia mexicana": "Western Bluebird",
  "Ephippiorhynchus senegalensis": "Saddle-billed Stork",
  "Cathartes aura": "Turkey Vulture",
  "Myadestes townsendi": "Townsend's Solitaire",
  "Cathartes burrovianus": "Lesser Yellow-headed Vulture",
  "Sarcoramphus papa": "King Vulture",
  "Coragyps atratus": "Black Vulture",
  "Strix nebulosa": "Great Gray Owl",
  "Anastomus lamelligerus": "African Openbill",
  "Pluvialis squatarola": "Black-bellied Plover",
  "Gymnogyps californianus": "California Condor",
  "Muscicapa striata": "Spotted Flycatcher",
  "Charadrius vociferus": "Killdeer",
  "Charadrius wilsonia": "Charadrius wilsonia",
  "Charadrius melodus": "Piping Plover",
  "Phoenicurus phoenicurus": "Common Redstart",
  "Phoenicurus ochruros": "Black Redstart",
  "Charadrius dubius": "Little Ringed Plover",
  "Eumomota superciliosa": "Turquoise-browed Motmot",
  "Anas querquedula": "Anas querquedula",
  "Himantopus mexicanus": "Black-necked Stilt",
  "Haematopus bachmani": "Black Oystercatcher",
  "Pica pica": "Eurasian Magpie",
  "Haematopus ostralegus": "Eurasian Oystercatcher",
  "Haematopus unicolor": "Variable Oystercatcher",
  "Vanellus vanellus": "Northern Lapwing",
  "Vanellus spinosus": "Spur-winged Lapwing",
  "Vanellus armatus": "Blacksmith Lapwing",
  "Luscinia svecica": "Bluethroat",
  "Columbina inca": "Inca Dove",
  "Recurvirostra avosetta": "Pied Avocet",
  "Phasianus colchicus": "Ring-necked Pheasant",
  "Pluvialis dominica": "American Golden-Plover",
  "Cinclus mexicanus": "American Dipper",
  "Erithacus rubecula": "European Robin",
  "Melanerpes aurifrons": "Golden-fronted Woodpecker",
  "Charadrius hiaticula": "Common Ringed Plover",
  "Egretta gularis": "Western Reef-Heron",
  "Egretta caerulea": "Little Blue Heron",
  "Egretta tricolor": "Tricolored Heron",
  "Egretta thula": "Snowy Egret",
  "Egretta garzetta": "Little Egret",
  "Egretta sacra": "Pacific Reef-Heron",
  "Monticola solitarius": "Blue Rock-Thrush",
  "Ardea cocoi": "Cocoi Heron",
  "Ardea cinerea": "Gray Heron",
  "Ardea herodias": "Great Blue Heron",
  "Nycticorax nycticorax": "Black-crowned Night Heron",
  "Turdus rufopalliatus": "Rufous-backed Robin",
  "Ardeola ralloides": "Squacco Heron",
  "Nyctanassa violacea": "Yellow-crowned Night Heron",
  "Aramides cajaneus": "Gray-cowled Wood-Rail",
  "Bubulcus ibis": "Western Cattle Egret",
  "Butorides virescens": "Green Heron",
  "Porphyrio martinicus": "Porphyrio martinicus",
  "Botaurus lentiginosus": "American Bittern",
  "Cochlearius cochlearius": "Boat-billed Heron",
  "Anhinga novaehollandiae": "Australasian Darter",
  "Anhinga rufa": "African Darter",
  "Melozone fusca": "Canyon Towhee",
  "Aquila chrysaetos": "Golden Eagle",
  "Hylocichla mustelina": "Wood Thrush",
  "Aphelocoma wollweberi": "Mexican Jay",
  "Accipiter striatus": "Sharp-shinned Hawk",
  "Accipiter nisus": "Eurasian Sparrowhawk",
  "Accipiter gentilis": "Eurasian Goshawk",
  "Egretta rufescens": "Reddish Egret",
  "Bucephala clangula": "Common Goldeneye",
  "Anous stolidus": "Brown Noddy",
  "Actitis macularius": "Spotted Sandpiper",
  "Ardea purpurea": "Purple Heron",
  "Todiramphus chloris": "Collared Kingfisher",
  "Grus americana": "Whooping Crane",
  "Himantopus himantopus": "Black-winged Stilt",
  "Glaucidium gnoma": "Northern Pygmy-Owl",
  "Circus approximans": "Swamp Harrier",
  "Circus aeruginosus": "Western Marsh Harrier",
  "Phalacrocorax sulcirostris": "Little Black Cormorant",
  "Buteo albonotatus": "Zone-tailed Hawk",
  "Butorides striata": "Striated Heron",
  "Platalea ajaja": "Roseate Spoonbill",
  "Buteo brachyurus": "Short-tailed Hawk",
  "Ardea alba": "Great Egret",
  "Buteo swainsoni": "Swainson's Hawk",
  "Alectoris rufa": "Red-legged Partridge",
  "Buteo lineatus": "Red-shouldered Hawk",
  "Buteo jamaicensis": "Red-tailed Hawk",
  "Charadrius nivosus": "Charadrius nivosus",
  "Tringa incana": "Wandering Tattler",
  "Tringa semipalmata": "Willet",
  "Terathopius ecaudatus": "Bateleur",
  "Gallinago delicata": "Wilson's Snipe",
  "Buteogallus anthracinus": "Common Black Hawk",
  "Chroicocephalus philadelphia": "Bonaparte's Gull",
  "Circaetus gallicus": "Short-toed Snake-Eagle",
  "Chroicocephalus novaehollandiae": "Silver Gull",
  "Chroicocephalus ridibundus": "Black-headed Gull",
  "Leucophaeus atricilla": "Laughing Gull",
  "Leucophaeus pipixcan": "Franklin's Gull",
  "Onychoprion fuscatus": "Sooty Tern",
  "Sternula antillarum": "Least Tern",
  "Hydroprogne caspia": "Caspian Tern",
  "Thalasseus maximus": "Royal Tern",
  "Thalasseus bergii": "Great Crested Tern",
  "Elanus leucurus": "White-tailed Kite",
  "Alopochen aegyptiaca": "Egyptian Goose",
  "Streptopelia senegalensis": "Streptopelia senegalensis",
  "Gerygone igata": "Gray Gerygone",
  "Haliaeetus leucocephalus": "Bald Eagle",
  "Cistothorus platensis": "Grass Wren",
  "Haliaeetus vocifer": "Haliaeetus vocifer",
  "Bubo scandiacus": "Snowy Owl",
  "Ciccaba virgata": "Ciccaba virgata",
  "Bonasa umbellus": "Ruffed Grouse",
  "Busarellus nigricollis": "Black-collared Hawk",
  "Rostrhamus sociabilis": "Snail Kite",
  "Milvus milvus": "Red Kite",
  "Gyps fulvus": "Eurasian Griffon",
  "Ficedula hypoleuca": "European Pied Flycatcher",
  "Momotus coeruliceps": "Blue-capped Motmot",
  "Charadrius semipalmatus": "Semipalmated Plover",
  "Haliastur indus": "Brahminy Kite",
  "Gyps africanus": "White-backed Vulture",
  "Ictinia mississippiensis": "Mississippi Kite",
  "Dives dives": "Melodious Blackbird",
  "Baeolophus atricristatus": "Black-crested Titmouse",
  "Baeolophus bicolor": "Tufted Titmouse",
  "Baeolophus inornatus": "Oak Titmouse",
  "Melospiza melodia": "Song Sparrow",
  "Spinus spinus": "Eurasian Siskin",
  "Motacilla alba": "White Wagtail",
  "Certhia americana": "Brown Creeper",
  "Bucorvus leadbeateri": "Southern Ground-Hornbill",
  "Anthus pratensis": "Meadow Pipit",
  "Anthus rubescens": "American Pipit",
  "Tachycineta albilinea": "Mangrove Swallow",
  "Poecile carolinensis": "Carolina Chickadee",
  "Poecile atricapillus": "Black-capped Chickadee",
  "Poecile gambeli": "Mountain Chickadee",
  "Poecile rufescens": "Chestnut-backed Chickadee",
  "Periparus ater": "Coal Tit",
  "Chlorophanes spiza": "Green Honeycreeper",
  "Estrilda astrild": "Common Waxbill",
  "Cyanistes caeruleus": "Eurasian Blue Tit",
  "Sphyrapicus varius": "Yellow-bellied Sapsucker",
  "Petrochelidon pyrrhonota": "Cliff Swallow",
  "Troglodytes pacificus": "Pacific Wren",
  "Troglodytes hiemalis": "Winter Wren",
  "Passer montanus": "Eurasian Tree Sparrow",
  "Passer domesticus": "House Sparrow",
  "Aphelocoma californica": "California Scrub-Jay",
  "Amazilia yucatanensis": "Buff-bellied Hummingbird",
  "Amazilia tzacatl": "Rufous-tailed Hummingbird",
  "Dicrurus adsimilis": "Fork-tailed Drongo",
  "Amazilia violiceps": "Amazilia violiceps",
  "Lonchura punctulata": "Scaly-breasted Munia",
  "Tigrisoma mexicanum": "Bare-throated Tiger-Heron",
  "Porphyrio melanotus melanotus": "",
  "Melanitta americana": "Black Scoter",
  "Spizella pallida": "Clay-colored Sparrow",
  "Amazilia rutila": "Cinnamon Hummingbird",
  "Zenaida aurita": "Zenaida Dove",
  "Prunella modularis": "Dunnock",
  "Falco tinnunculus": "Eurasian Kestrel",
  "Ixoreus naevius": "Varied Thrush",
  "Archilochus colubris": "Ruby-throated Hummingbird",
  "Lampornis clemenciae": "Blue-throated Mountain-gem",
  "Myiarchus tuberculifer": "Dusky-capped Flycatcher",
  "Setophaga ruticilla": "American Redstart",
  "Myiarchus tyrannulus": "Brown-crested Flycatcher",
  "Zosterops lateralis": "Silvereye",
  "Zonotrichia leucophrys": "White-crowned Sparrow",
  "Agelaius phoeniceus": "Red-winged Blackbird",
  "Parus major": "Great Tit",
  "Zonotrichia capensis": "Rufous-collared Sparrow",
  "Oreothlypis peregrina": "Oreothlypis peregrina",
  "Oreothlypis celata": "Oreothlypis celata",
  "Oreothlypis ruficapilla": "Oreothlypis ruficapilla",
  "Geothlypis philadelphia": "Mourning Warbler",
  "Geothlypis formosa": "Kentucky Warbler",
  "Setophaga tigrina": "Cape May Warbler",
  "Setophaga americana": "Northern Parula",
  "Setophaga magnolia": "Magnolia Warbler",
  "Setophaga castanea": "Bay-breasted Warbler",
  "Setophaga fusca": "Blackburnian Warbler",
  "Setophaga petechia": "Yellow Warbler",
  "Setophaga striata": "Blackpoll Warbler",
  "Setophaga palmarum": "Palm Warbler",
  "Setophaga pinus": "Pine Warbler",
  "Setophaga coronata": "Yellow-rumped Warbler",
  "Setophaga dominica": "Yellow-throated Warbler",
  "Campylopterus hemileucurus": "Violet Sabrewing",
  "Vireo cassinii": "Cassin's Vireo",
  "Setophaga nigrescens": "Black-throated Gray Warbler",
  "Setophaga townsendi": "Townsend's Warbler",
  "Setophaga occidentalis": "Hermit Warbler",
  "Setophaga chrysoparia": "Golden-cheeked Warbler",
  "Setophaga virens": "Black-throated Green Warbler",
  "Cardellina canadensis": "Canada Warbler",
  "Cardellina rubra": "Red Warbler",
  "Aphelocoma coerulescens": "Florida Scrub-Jay",
  "Melanerpes erythrocephalus": "Red-headed Woodpecker",
  "Emberiza calandra": "Corn Bunting",
  "Acanthis flammea": "Common Redpoll",
  "Spinus pinus": "Pine Siskin",
  "Thraupis abbas": "Yellow-winged Tanager",
  "Spinus psaltria": "Lesser Goldfinch",
  "Spinus lawrencei": "Lawrence's Goldfinch",
  "Spinus tristis": "American Goldfinch",
  "Threskiornis aethiopicus": "African Sacred Ibis",
  "Gygis alba": "White Tern",
  "Tachycineta bicolor": "Tree Swallow",
  "Larus dominicanus dominicanus": "Kelp Gull (dominicanus)",
  "Lonchura oryzivora": "Lonchura oryzivora",
  "Haematopus palliatus": "American Oystercatcher",
  "Chloris chloris": "European Greenfinch",
  "Accipiter cooperii": "Cooper's Hawk",
  "Vireo solitarius": "Blue-headed Vireo",
  "Selasphorus platycercus": "Broad-tailed Hummingbird",
  "Chroicocephalus scopulinus": "Chroicocephalus scopulinus",
  "Aechmophorus occidentalis": "Western Grebe",
  "Hemiphaga novaeseelandiae": "New Zealand Pigeon",
  "Xema sabini": "Sabine's Gull",
  "Ramphastos sulfuratus": "Keel-billed Toucan",
  "Dacelo novaeguineae": "Laughing Kookaburra",
  "Fulica atra": "Eurasian Coot",
  "Hirundo rustica erythrogaster": "Barn Swallow (American)",
  "Calypte costae": "Costa's Hummingbird",
  "Calypte anna": "Anna's Hummingbird",
  "Colaptes auratus cafer": "",
  "Sula nebouxii": "Blue-footed Booby",
  "Copsychus saularis": "Oriental Magpie-Robin",
  "Selasphorus sasin": "Allen's Hummingbird",
  "Selasphorus rufus": "Rufous Hummingbird",
  "Calothorax lucifer": "Lucifer Hummingbird",
  "Pycnonotus barbatus": "Common Bulbul",
  "Larus glaucescens × occidentalis": "Glaucous-winged Gull",
  "Aphelocoma woodhouseii": "Woodhouse's Scrub-Jay",
  "Florisuga mellivora": "White-necked Jacobin",
  "Haematopus finschi": "South Island Oystercatcher",
  "Falcipennis canadensis": "Falcipennis canadensis",
  "Archilochus alexandri": "Black-chinned Hummingbird",
  "Circus cyaneus": "Hen Harrier",
  "Ardea alba modesta": "Great Egret (modesta)",
  "Myiarchus crinitus": "Great Crested Flycatcher",
  "Buteo regalis": "Ferruginous Hawk",
  "Aeronautes saxatalis": "White-throated Swift",
  "Chaetura vauxi": "Vaux's Swift",
  "Chaetura pelagica": "Chimney Swift",
  "Setophaga pensylvanica": "Chestnut-sided Warbler",
  "Lanius ludovicianus": "Loggerhead Shrike",
  "Anhinga anhinga": "Anhinga",
  "Acridotheres tristis": "Common Myna",
  "Sitta pygmaea": "Pygmy Nuthatch",
  "Actophilornis africanus": "African Jacana",
  "Sitta canadensis": "Red-breasted Nuthatch",
  "Sitta europaea": "Eurasian Nuthatch",
  "Sitta pusilla": "Brown-headed Nuthatch",
  "Apus apus": "Common Swift",
  "Sturnus vulgaris": "European Starling",
  "Seiurus aurocapilla": "Ovenbird",
  "Motacilla flava": "Western Yellow Wagtail",
  "Vireo griseus": "White-eyed Vireo",
  "Toxostoma longirostre": "Long-billed Thrasher",
  "Calidris alba": "Sanderling",
  "Toxostoma redivivum": "California Thrasher",
  "Gallinula galeata": "Common Gallinule",
  "Calidris himantopus": "Stilt Sandpiper",
  "Eugenes fulgens": "Rivoli's Hummingbird",
  "Icterus wagleri": "Black-vented Oriole",
  "Icterus parisorum": "Scott's Oriole",
  "Buteo platypterus": "Broad-winged Hawk",
  "Gallinago gallinago": "Common Snipe",
  "Icterus spurius": "Orchard Oriole",
  "Calidris minutilla": "Least Sandpiper",
  "Dumetella carolinensis": "Gray Catbird",
  "Porphyrio hochstetteri": "South Island Takahe",
  "Calidris fuscicollis": "White-rumped Sandpiper",
  "Phalaropus tricolor": "Wilson's Phalarope",
  "Colaptes auratus auratus": "",
  "Melanotis caerulescens": "Blue Mockingbird",
  "Tiaris olivaceus": "Yellow-faced Grassquit",
  "Oreoscoptes montanus": "Sage Thrasher",
  "Limnodromus scolopaceus": "Long-billed Dowitcher",
  "Tringa solitaria": "Solitary Sandpiper",
  "Sitta carolinensis": "White-breasted Nuthatch",
  "Tringa totanus": "Common Redshank",
  "Dendrocygna autumnalis": "Black-bellied Whistling-Duck",
  "Dendrocygna viduata": "White-faced Whistling-Duck",
  "Dendrocygna bicolor": "Fulvous Whistling-Duck",
  "Icterus abeillei": "Black-backed Oriole",
  "Vanellus chilensis": "Southern Lapwing",
  "Cygnus buccinator": "Trumpeter Swan",
  "Cygnus cygnus": "Whooper Swan",
  "Cygnus columbianus": "Tundra Swan",
  "Cygnus olor": "Mute Swan",
  "Icterus galbula": "Baltimore Oriole",
  "Anas platyrhynchos": "Mallard",
  "Anas acuta": "Northern Pintail",
  "Anas crecca": "Green-winged Teal",
  "Anas cyanoptera": "Anas cyanoptera",
  "Anas fulvigula": "Mottled Duck",
  "Anas discors": "Anas discors",
  "Anas strepera": "Anas strepera",
  "Anas clypeata": "Anas clypeata",
  "Anas chlorotis": "Brown Teal",
  "Rhipidura leucophrys": "Willie-wagtail",
  "Anas americana": "Anas americana",
  "Bucephala albeola": "Bufflehead",
  "Mergus serrator": "Red-breasted Merganser",
  "Mergus merganser": "Common Merganser",
  "Anser anser": "Graylag Goose",
  "Anser albifrons": "Greater White-fronted Goose",
  "Somateria mollissima": "Common Eider",
  "Rallus obsoletus": "Ridgway's Rail",
  "Platycercus elegans": "Crimson Rosella",
  "Melanitta fusca": "Velvet Scoter",
  "Milvus migrans": "Black Kite",
  "Gelochelidon nilotica": "Gull-billed Tern",
  "Ninox novaeseelandiae novaeseelandiae": "",
  "Melanitta perspicillata": "Surf Scoter",
  "Aythya collaris": "Ring-necked Duck",
  "Aythya ferina": "Common Pochard",
  "Aythya fuligula": "Tufted Duck",
  "Numenius americanus": "Long-billed Curlew",
  "Chen caerulescens": "Chen caerulescens",
  "Chamaea fasciata": "Wrentit",
  "Branta canadensis": "Canada Goose",
  "Thalasseus elegans": "Elegant Tern",
  "Branta sandvicensis": "Hawaiian Goose",
  "Aythya americana": "Redhead",
  "Aix sponsa": "Wood Duck",
  "Lophodytes cucullatus": "Hooded Merganser",
  "Histrionicus histrionicus": "Harlequin Duck",
  "Aratinga nenday": "Nanday Parakeet",
  "Psittacara holochlorus": "Green Parakeet",
  "Cairina moschata": "Muscovy Duck",
  "Netta rufina": "Red-crested Pochard",
  "Psittacara erythrogenys": "Red-masked Parakeet",
  "Sayornis saya": "Say's Phoebe",
  "Aythya valisineria": "Canvasback",
  "Picoides albolarvatus": "Picoides albolarvatus",
  "Vermivora cyanoptera": "Blue-winged Warbler",
  "Corvus caurinus": "Corvus caurinus",
  "Asio otus": "Long-eared Owl",
  "Corvus brachyrhynchos": "American Crow",
  "Clangula hyemalis": "Long-tailed Duck",
  "Chenonetta jubata": "Maned Duck",
  "Thalasseus sandvicensis": "Sandwich Tern",
  "Eolophus roseicapilla": "Galah",
  "Colaptes rubiginosus": "Golden-olive Woodpecker",
  "Meleagris gallopavo silvestris": "",
  "Ptiliogonys cinereus": "Gray Silky-flycatcher",
  "Elanoides forficatus": "Swallow-tailed Kite",
  "Carduelis carduelis": "European Goldfinch",
  "Cassiculus melanicterus": "Yellow-winged Cacique",
  "Dendragapus fuliginosus": "Sooty Grouse",
  "Psaltriparus minimus": "Bushtit",
  "Aegithalos caudatus": "Long-tailed Tit",
  "Zosterops lateralis lateralis": "",
  "Haliaeetus leucogaster": "Haliaeetus leucogaster",
  "Uria aalge": "Common Murre",
  "Tringa semipalmata inornatus": "Willet",
  "Alauda arvensis": "Eurasian Skylark",
  "Galerida cristata": "Crested Lark",
  "Delichon urbicum": "Western House-Martin",
  "Helmitheros vermivorum": "Worm-eating Warbler",
  "Hylocharis leucotis": "Hylocharis leucotis",
  "Mimus polyglottos": "Northern Mockingbird",
  "Gymnorhina tibicen": "Australian Magpie",
  "Alcedo atthis": "Common Kingfisher",
  "Streptopelia chinensis": "Streptopelia chinensis",
  "Bombycilla cedrorum": "Cedar Waxwing",
  "Bombycilla garrulus": "Bohemian Waxwing",
  "Tadorna tadorna": "Common Shelduck",
  "Petroica australis australis": "",
  "Amazona autumnalis": "Red-lored Parrot",
  "Dendragapus obscurus": "Dusky Grouse",
  "Catherpes mexicanus": "Canyon Wren",
  "Tadorna ferruginea": "Ruddy Shelduck",
  "Campylorhynchus brunneicapillus": "Cactus Wren",
  "Campylorhynchus rufinucha": "Rufous-naped Wren",
  "Rhipidura fuliginosa": "New Zealand Fantail",
  "Polioptila melanura": "Black-tailed Gnatcatcher",
  "Pelecanus occidentalis carolinensis": "Brown Pelican (Atlantic)",
  "Melozone aberti": "Abert's Towhee",
  "Melozone crissalis": "California Towhee",
  "Thryothorus ludovicianus": "Carolina Wren",
  "Parabuteo unicinctus": "Harris's Hawk",
  "Anas platyrhynchos domesticus": "Mallard",
  "Troglodytes aedon": "House Wren",
  "Buteo lineatus elegans": "Red-shouldered Hawk (elegans)",
  "Thamnophilus doliatus": "Barred Antshrike",
  "Thryomanes bewickii": "Bewick's Wren",
  "Tadorna variegata": "Paradise Shelduck",
  "Myioborus miniatus": "Slate-throated Redstart",
  "Phalacrocorax varius varius": "",
  "Myioborus pictus": "Painted Redstart",
  "Larus argentatus smithsonianus": "Herring Gull (American)",
  "Parkesia motacilla": "Louisiana Waterthrush",
  "Sula granti": "Nazca Booby",
  "Ara macao": "Scarlet Macaw",
  "Peucaea ruficauda": "Stripe-headed Sparrow",
  "Calidris subruficollis": "Buff-breasted Sandpiper",
  "Phoenicopterus roseus": "Greater Flamingo",
  "Morus bassanus": "Northern Gannet",
  "Pelecanus occidentalis californicus": "Brown Pelican (California)",
  "Glaucidium brasilianum": "Ferruginous Pygmy-Owl",
  "Oxyura jamaicensis": "Ruddy Duck",
  "Myiarchus cinerascens": "Ash-throated Flycatcher",
  "Chloroceryle americana": "Green Kingfisher",
  "Sturnella neglecta": "Western Meadowlark",
  "Ramphastos ambiguus": "Yellow-throated Toucan",
  "Paroaria coronata": "Red-crested Cardinal",
  "Buteo buteo": "Common Buzzard",
  "Myiodynastes luteiventris": "Sulphur-bellied Flycatcher",
  "Contopus sordidulus": "Western Wood-Pewee",
  "Corvus corone": "Carrion Crow",
  "Cyanoramphus novaezelandiae": "Red-crowned Parakeet",
  "Contopus virens": "Eastern Wood-Pewee",
  "Contopus pertinax": "Greater Pewee",
  "Contopus cooperi": "Olive-sided Flycatcher",
  "Larus argentatus": "Herring Gull",
  "Halcyon smyrnensis": "White-throated Kingfisher",
  "Onychognathus morio": "Red-winged Starling",
  "Cyanocompsa parellina": "Blue Bunting",
  "Cistothorus palustris": "Marsh Wren",
  "Tyto alba": "Barn Owl",
  "Trogon caligatus": "Gartered Trogon",
  "Corvus monedula": "Eurasian Jackdaw",
  "Corvus ossifragus": "Fish Crow",
  "Spheniscus demersus": "African Penguin",
  "Corvus frugilegus": "Rook",
  "Corvus splendens": "House Crow",
  "Branta bernicla": "Brant",
  "Larus hyperboreus": "Glaucous Gull",
  "Columba livia domestica": "Rock Pigeon",
  "Garrulus glandarius": "Eurasian Jay",
  "Anser anser domesticus": "Graylag Goose",
  "Mitrephanes phaeocercus": "Tufted Flycatcher",
  "Ardenna creatopus": "Pink-footed Shearwater",
  "Ardenna gravis": "Great Shearwater",
  "None": "None",
};
