// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/nms.dart';
import 'api/pipeline.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -313277095;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_rackery',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<RawDetection>> crateApiNmsApplyNms({
    required List<RawDetection> detections,
  });

  Future<ClassificationResult> crateApiPipelineClassifyCrop({
    required List<int> cropBytes,
    List<String>? allowedSpecies,
    required bool isFallback,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<String> crateApiPipelineInitPipeline({
    required List<int> detectorModelBytes,
    required List<int> classifierModelBytes,
    required List<int> embeddingsBytes,
    required String labelsJson,
  });

  Future<List<RawDetection>> crateApiNmsParseTileDetections({
    required List<double> outBoxes,
    required List<double> outScores,
    required List<double> outClasses,
    required BigInt batchIdx,
    required BigInt maxDet,
    required BigInt count,
    required U32Array4 tile,
    required int origW,
    required int origH,
  });

  Stream<PipelineEvent> crateApiPipelineProcessPipeline({
    required List<int> fileBytes,
    List<String>? allowedSpecies,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<RawDetection>> crateApiNmsApplyNms({
    required List<RawDetection> detections,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_raw_detection(detections, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_raw_detection,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNmsApplyNmsConstMeta,
        argValues: [detections],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNmsApplyNmsConstMeta =>
      const TaskConstMeta(debugName: "apply_nms", argNames: ["detections"]);

  @override
  Future<ClassificationResult> crateApiPipelineClassifyCrop({
    required List<int> cropBytes,
    List<String>? allowedSpecies,
    required bool isFallback,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(cropBytes, serializer);
          sse_encode_opt_list_String(allowedSpecies, serializer);
          sse_encode_bool(isFallback, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_classification_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPipelineClassifyCropConstMeta,
        argValues: [cropBytes, allowedSpecies, isFallback],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPipelineClassifyCropConstMeta =>
      const TaskConstMeta(
        debugName: "classify_crop",
        argNames: ["cropBytes", "allowedSpecies", "isFallback"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiPipelineInitPipeline({
    required List<int> detectorModelBytes,
    required List<int> classifierModelBytes,
    required List<int> embeddingsBytes,
    required String labelsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(detectorModelBytes, serializer);
          sse_encode_list_prim_u_8_loose(classifierModelBytes, serializer);
          sse_encode_list_prim_u_8_loose(embeddingsBytes, serializer);
          sse_encode_String(labelsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPipelineInitPipelineConstMeta,
        argValues: [
          detectorModelBytes,
          classifierModelBytes,
          embeddingsBytes,
          labelsJson,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPipelineInitPipelineConstMeta =>
      const TaskConstMeta(
        debugName: "init_pipeline",
        argNames: [
          "detectorModelBytes",
          "classifierModelBytes",
          "embeddingsBytes",
          "labelsJson",
        ],
      );

  @override
  Future<List<RawDetection>> crateApiNmsParseTileDetections({
    required List<double> outBoxes,
    required List<double> outScores,
    required List<double> outClasses,
    required BigInt batchIdx,
    required BigInt maxDet,
    required BigInt count,
    required U32Array4 tile,
    required int origW,
    required int origH,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(outBoxes, serializer);
          sse_encode_list_prim_f_32_loose(outScores, serializer);
          sse_encode_list_prim_f_32_loose(outClasses, serializer);
          sse_encode_usize(batchIdx, serializer);
          sse_encode_usize(maxDet, serializer);
          sse_encode_usize(count, serializer);
          sse_encode_u_32_array_4(tile, serializer);
          sse_encode_u_32(origW, serializer);
          sse_encode_u_32(origH, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_raw_detection,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNmsParseTileDetectionsConstMeta,
        argValues: [
          outBoxes,
          outScores,
          outClasses,
          batchIdx,
          maxDet,
          count,
          tile,
          origW,
          origH,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNmsParseTileDetectionsConstMeta =>
      const TaskConstMeta(
        debugName: "parse_tile_detections",
        argNames: [
          "outBoxes",
          "outScores",
          "outClasses",
          "batchIdx",
          "maxDet",
          "count",
          "tile",
          "origW",
          "origH",
        ],
      );

  @override
  Stream<PipelineEvent> crateApiPipelineProcessPipeline({
    required List<int> fileBytes,
    List<String>? allowedSpecies,
  }) {
    final stream = RustStreamSink<PipelineEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_list_prim_u_8_loose(fileBytes, serializer);
            sse_encode_opt_list_String(allowedSpecies, serializer);
            sse_encode_StreamSink_pipeline_event_Sse(stream, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiPipelineProcessPipelineConstMeta,
          argValues: [fileBytes, allowedSpecies, stream],
          apiImpl: this,
        ),
      ),
    );
    return stream.stream;
  }

  TaskConstMeta get kCrateApiPipelineProcessPipelineConstMeta =>
      const TaskConstMeta(
        debugName: "process_pipeline",
        argNames: ["fileBytes", "allowedSpecies", "stream"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<PipelineEvent> dco_decode_StreamSink_pipeline_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PipelineResult dco_decode_box_autoadd_pipeline_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pipeline_result(raw);
  }

  @protected
  ClassificationResult dco_decode_classification_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return ClassificationResult(species: dco_decode_list_String(arr[0]));
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<NativeBirdResult> dco_decode_list_native_bird_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_native_bird_result).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RawDetection> dco_decode_list_raw_detection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_raw_detection).toList();
  }

  @protected
  NativeBirdResult dco_decode_native_bird_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return NativeBirdResult(
      species: dco_decode_String(arr[0]),
      possibleSpecies: dco_decode_list_String(arr[1]),
      confidence: dco_decode_f_64(arr[2]),
      boxX: dco_decode_u_32(arr[3]),
      boxY: dco_decode_u_32(arr[4]),
      boxW: dco_decode_u_32(arr[5]),
      boxH: dco_decode_u_32(arr[6]),
      centerColor: dco_decode_list_prim_f_64_strict(arr[7]),
      cropJpgBytes: dco_decode_list_prim_u_8_strict(arr[8]),
    );
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  PipelineEvent dco_decode_pipeline_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PipelineEvent_Progress(dco_decode_String(raw[1]));
      case 1:
        return PipelineEvent_Complete(
          dco_decode_box_autoadd_pipeline_result(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  PipelineResult dco_decode_pipeline_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PipelineResult(
      birds: dco_decode_list_native_bird_result(arr[0]),
      detectionMs: dco_decode_u_64(arr[1]),
      classificationMs: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  RawDetection dco_decode_raw_detection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RawDetection(
      globalX: dco_decode_u_32(arr[0]),
      globalY: dco_decode_u_32(arr[1]),
      localW: dco_decode_u_32(arr[2]),
      localH: dco_decode_u_32(arr[3]),
      score: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  U32Array4 dco_decode_u_32_array_4(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U32Array4(dco_decode_list_prim_u_32_strict(raw));
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<PipelineEvent> sse_decode_StreamSink_pipeline_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PipelineResult sse_decode_box_autoadd_pipeline_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pipeline_result(deserializer));
  }

  @protected
  ClassificationResult sse_decode_classification_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_species = sse_decode_list_String(deserializer);
    return ClassificationResult(species: var_species);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativeBirdResult> sse_decode_list_native_bird_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeBirdResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_bird_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RawDetection> sse_decode_list_raw_detection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RawDetection>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_raw_detection(deserializer));
    }
    return ans_;
  }

  @protected
  NativeBirdResult sse_decode_native_bird_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_species = sse_decode_String(deserializer);
    var var_possibleSpecies = sse_decode_list_String(deserializer);
    var var_confidence = sse_decode_f_64(deserializer);
    var var_boxX = sse_decode_u_32(deserializer);
    var var_boxY = sse_decode_u_32(deserializer);
    var var_boxW = sse_decode_u_32(deserializer);
    var var_boxH = sse_decode_u_32(deserializer);
    var var_centerColor = sse_decode_list_prim_f_64_strict(deserializer);
    var var_cropJpgBytes = sse_decode_list_prim_u_8_strict(deserializer);
    return NativeBirdResult(
      species: var_species,
      possibleSpecies: var_possibleSpecies,
      confidence: var_confidence,
      boxX: var_boxX,
      boxY: var_boxY,
      boxW: var_boxW,
      boxH: var_boxH,
      centerColor: var_centerColor,
      cropJpgBytes: var_cropJpgBytes,
    );
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PipelineEvent sse_decode_pipeline_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return PipelineEvent_Progress(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_pipeline_result(deserializer);
        return PipelineEvent_Complete(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  PipelineResult sse_decode_pipeline_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_birds = sse_decode_list_native_bird_result(deserializer);
    var var_detectionMs = sse_decode_u_64(deserializer);
    var var_classificationMs = sse_decode_u_64(deserializer);
    return PipelineResult(
      birds: var_birds,
      detectionMs: var_detectionMs,
      classificationMs: var_classificationMs,
    );
  }

  @protected
  RawDetection sse_decode_raw_detection(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_globalX = sse_decode_u_32(deserializer);
    var var_globalY = sse_decode_u_32(deserializer);
    var var_localW = sse_decode_u_32(deserializer);
    var var_localH = sse_decode_u_32(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    return RawDetection(
      globalX: var_globalX,
      globalY: var_globalY,
      localW: var_localW,
      localH: var_localH,
      score: var_score,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  U32Array4 sse_decode_u_32_array_4(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_32_strict(deserializer);
    return U32Array4(inner);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_pipeline_event_Sse(
    RustStreamSink<PipelineEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_pipeline_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_pipeline_result(
    PipelineResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pipeline_result(self, serializer);
  }

  @protected
  void sse_encode_classification_result(
    ClassificationResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.species, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_bird_result(
    List<NativeBirdResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_bird_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_raw_detection(
    List<RawDetection> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_raw_detection(item, serializer);
    }
  }

  @protected
  void sse_encode_native_bird_result(
    NativeBirdResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.species, serializer);
    sse_encode_list_String(self.possibleSpecies, serializer);
    sse_encode_f_64(self.confidence, serializer);
    sse_encode_u_32(self.boxX, serializer);
    sse_encode_u_32(self.boxY, serializer);
    sse_encode_u_32(self.boxW, serializer);
    sse_encode_u_32(self.boxH, serializer);
    sse_encode_list_prim_f_64_strict(self.centerColor, serializer);
    sse_encode_list_prim_u_8_strict(self.cropJpgBytes, serializer);
  }

  @protected
  void sse_encode_opt_list_String(
    List<String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_pipeline_event(PipelineEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PipelineEvent_Progress(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case PipelineEvent_Complete(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_pipeline_result(field0, serializer);
    }
  }

  @protected
  void sse_encode_pipeline_result(
    PipelineResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_native_bird_result(self.birds, serializer);
    sse_encode_u_64(self.detectionMs, serializer);
    sse_encode_u_64(self.classificationMs, serializer);
  }

  @protected
  void sse_encode_raw_detection(RawDetection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.globalX, serializer);
    sse_encode_u_32(self.globalY, serializer);
    sse_encode_u_32(self.localW, serializer);
    sse_encode_u_32(self.localH, serializer);
    sse_encode_f_32(self.score, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_32_array_4(U32Array4 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_32_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
