// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<PrepareTilesResult?> prepareTiles({
  required List<int> fileBytes,
  required int targetW,
  required int targetH,
  List<Uint32List>? customTiles,
}) => RustLib.instance.api.crateApiImageUtilsPrepareTiles(
  fileBytes: fileBytes,
  targetW: targetW,
  targetH: targetH,
  customTiles: customTiles,
);

class PrepareTilesResult {
  final List<Uint8List> tilePixels;
  final List<Uint32List> tileRects;
  final int origW;
  final int origH;

  const PrepareTilesResult({
    required this.tilePixels,
    required this.tileRects,
    required this.origW,
    required this.origH,
  });

  @override
  int get hashCode =>
      tilePixels.hashCode ^
      tileRects.hashCode ^
      origW.hashCode ^
      origH.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrepareTilesResult &&
          runtimeType == other.runtimeType &&
          tilePixels == other.tilePixels &&
          tileRects == other.tileRects &&
          origW == other.origW &&
          origH == other.origH;
}
