// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compute_ahash`, `convert_heic_to_jpeg`, `extract_exif`, `is_leap_year`, `load_heif_lib`, `parse_exif_date`, `parse_gps_coord`, `process_single_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HeifErrorRaw`, `HeifLib`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Process a batch of image files: extract EXIF, compute perceptual hash,
/// and convert HEIC/HEIF to JPEG. Results stream to Dart as each file
/// completes. Files are sorted by size (ascending) so the smallest finish
/// first.
Stream<IngestionFileResult> ingestFiles({
  required List<String> paths,
  required String heicCacheDir,
}) => RustLib.instance.api.crateApiIngestionIngestFiles(
  paths: paths,
  heicCacheDir: heicCacheDir,
);

/// Per-file ingestion result streamed back to Dart.
class IngestionFileResult {
  final String path;
  final String processedPath;
  final PlatformInt64? exifDateMs;
  final double? latitude;
  final double? longitude;
  final String? visualHash;
  final BigInt fileSize;

  const IngestionFileResult({
    required this.path,
    required this.processedPath,
    this.exifDateMs,
    this.latitude,
    this.longitude,
    this.visualHash,
    required this.fileSize,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      processedPath.hashCode ^
      exifDateMs.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      visualHash.hashCode ^
      fileSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IngestionFileResult &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          processedPath == other.processedPath &&
          exifDateMs == other.exifDateMs &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          visualHash == other.visualHash &&
          fileSize == other.fileSize;
}
