// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Parse raw detection outputs for a single tile within a (possibly batched)
/// result.
///
/// * `batch_idx` — which element in the batch this tile corresponds to
/// * `max_det`   — maximum detections per batch element (from output shape)
/// * `count`     — actual number of valid detections for this tile
Future<List<RawDetection>> parseTileDetections({
  required List<double> outBoxes,
  required List<double> outScores,
  required List<double> outClasses,
  required BigInt batchIdx,
  required BigInt maxDet,
  required BigInt count,
  required U32Array4 tile,
  required int origW,
  required int origH,
}) => RustLib.instance.api.crateApiNmsParseTileDetections(
  outBoxes: outBoxes,
  outScores: outScores,
  outClasses: outClasses,
  batchIdx: batchIdx,
  maxDet: maxDet,
  count: count,
  tile: tile,
  origW: origW,
  origH: origH,
);

/// Filter duplicate detections using IoU + centre-distance NMS.
///
/// Sorted by descending score so that the highest-confidence box for each
/// subject is always preferred. The coverage check is intentionally omitted
/// so that a small foreground bird enclosed by a larger background bird is
/// not incorrectly suppressed.
Future<List<RawDetection>> applyNms({required List<RawDetection> detections}) =>
    RustLib.instance.api.crateApiNmsApplyNms(detections: detections);

/// A single raw bounding-box detection from the EfficientDet model,
/// expressed in global image coordinates before NMS filtering.
class RawDetection {
  final int globalX;
  final int globalY;
  final int localW;
  final int localH;
  final double score;

  const RawDetection({
    required this.globalX,
    required this.globalY,
    required this.localW,
    required this.localH,
    required this.score,
  });

  @override
  int get hashCode =>
      globalX.hashCode ^
      globalY.hashCode ^
      localW.hashCode ^
      localH.hashCode ^
      score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawDetection &&
          runtimeType == other.runtimeType &&
          globalX == other.globalX &&
          globalY == other.globalY &&
          localW == other.localW &&
          localH == other.localH &&
          score == other.score;
}

class U32Array4 extends NonGrowableListView<int> {
  static const arraySize = 4;

  @internal
  Uint32List get inner => _inner;
  final Uint32List _inner;

  U32Array4(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U32Array4.init() : this(Uint32List(arraySize));
}
