// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'pipeline.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `build_tiles`, `classify_image`, `compute_center_color`, `infer_single_tile`, `prepare_tile_tensor`, `run_detection_concurrent`

Future<String> initPipeline({
  required List<int> detectorModelBytes,
  required List<int> classifierModelBytes,
  required List<int> embeddingsBytes,
  required String labelsJson,
}) => RustLib.instance.api.crateApiPipelineInitPipeline(
  detectorModelBytes: detectorModelBytes,
  classifierModelBytes: classifierModelBytes,
  embeddingsBytes: embeddingsBytes,
  labelsJson: labelsJson,
);

Stream<PipelineEvent> processPipeline({
  required List<int> fileBytes,
  List<String>? allowedSpecies,
}) => RustLib.instance.api.crateApiPipelineProcessPipeline(
  fileBytes: fileBytes,
  allowedSpecies: allowedSpecies,
);

/// Classify a single pre-cropped image (used for manual bounding boxes and
/// re-classification requests from Dart).
Future<ClassificationResult> classifyCrop({
  required List<int> cropBytes,
  List<String>? allowedSpecies,
  required bool isFallback,
}) => RustLib.instance.api.crateApiPipelineClassifyCrop(
  cropBytes: cropBytes,
  allowedSpecies: allowedSpecies,
  isFallback: isFallback,
);

class ClassificationResult {
  final List<String> species;

  const ClassificationResult({required this.species});

  @override
  int get hashCode => species.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClassificationResult &&
          runtimeType == other.runtimeType &&
          species == other.species;
}

class NativeBirdResult {
  final String species;
  final List<String> possibleSpecies;
  final double confidence;
  final int boxX;
  final int boxY;
  final int boxW;
  final int boxH;
  final Float64List centerColor;
  final Uint8List cropJpgBytes;

  const NativeBirdResult({
    required this.species,
    required this.possibleSpecies,
    required this.confidence,
    required this.boxX,
    required this.boxY,
    required this.boxW,
    required this.boxH,
    required this.centerColor,
    required this.cropJpgBytes,
  });

  @override
  int get hashCode =>
      species.hashCode ^
      possibleSpecies.hashCode ^
      confidence.hashCode ^
      boxX.hashCode ^
      boxY.hashCode ^
      boxW.hashCode ^
      boxH.hashCode ^
      centerColor.hashCode ^
      cropJpgBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeBirdResult &&
          runtimeType == other.runtimeType &&
          species == other.species &&
          possibleSpecies == other.possibleSpecies &&
          confidence == other.confidence &&
          boxX == other.boxX &&
          boxY == other.boxY &&
          boxW == other.boxW &&
          boxH == other.boxH &&
          centerColor == other.centerColor &&
          cropJpgBytes == other.cropJpgBytes;
}

@freezed
sealed class PipelineEvent with _$PipelineEvent {
  const PipelineEvent._();

  const factory PipelineEvent.progress(String field0) = PipelineEvent_Progress;
  const factory PipelineEvent.complete(PipelineResult field0) =
      PipelineEvent_Complete;
}

class PipelineResult {
  final List<NativeBirdResult> birds;
  final BigInt detectionMs;
  final BigInt classificationMs;

  const PipelineResult({
    required this.birds,
    required this.detectionMs,
    required this.classificationMs,
  });

  @override
  int get hashCode =>
      birds.hashCode ^ detectionMs.hashCode ^ classificationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PipelineResult &&
          runtimeType == other.runtimeType &&
          birds == other.birds &&
          detectionMs == other.detectionMs &&
          classificationMs == other.classificationMs;
}
